services:
  web_and_api:
    build: .
    container_name: agent_web
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:latest
    container_name: agent_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: agent_redis
    ports:
      - "6379:6379"

  neo4j:
    image: neo4j:latest
    container_name: agent_neo4j
    ports:
      - "7474:7474" # HTTP GUI
      - "7687:7687" # Bolt port
    environment:
      NEO4J_AUTH: neo4j/testpassword
    volumes:
      - neo4j_data:/data

volumes:
  mongo_data:
  neo4j_data:
